# Generated by Django 4.0.3 on 2022-03-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key',
            new_name='Keystring',
        ),
    ]
