# Generated by Django 4.0.3 on 2022-03-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_key_keystring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keystring',
            new_name='Key',
        ),
    ]
