# Generated by Django 4.0.3 on 2022-03-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_keystring_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='quality_source',
        ),
    ]
